# Generated by Django 4.2.7 on 2026-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=20),
        ),
    ]
