# Generated by Django 4.2.7 on 2026-01-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_called',
            field=models.BooleanField(default=False),
        ),
    ]
