# Generated by Django 5.2.9 on 2026-01-30 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_outlet_order_outlet_outletmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_day_start_hour', models.TimeField(default='04:00:00', help_text='Time when business day starts (e.g., 04:00 for 4 AM)')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text="Vendor's timezone (e.g., Asia/Kolkata, America/New_York)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='orders.outlet')),
            ],
        ),
    ]
