# Generated by Django 5.2.9 on 2026-01-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_vendorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorconfig',
            name='continuous_booking_counter',
            field=models.IntegerField(default=0, help_text='Counter for booking numbers, resets at start of each business day'),
        ),
    ]
