# Generated by Django 5.2.9 on 2026-01-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_vendorconfig_continuous_booking_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counter_number',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incremented counter number, resets daily per business day', null=True),
        ),
    ]
